# Generated by Django 2.1.7 on 2019-03-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
